<?php 
/**
 * eInfochips_Coupons4U extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	eInfochips
 * @package		eInfochips_Coupons4U
 * @copyright  	Copyright (c) 2014
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Coupon4U view template
 *
 * @category	eInfochips
 * @package		eInfochips_Coupons4U
 * @author Ultimate Module Creator
 */
?>
<?php $_coupon4u = $this->getCurrentCoupon4u();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title coupon4u-title">
	<h1><?php echo $_coupon4u->getCouponid(); ?></h1>
</div>
<div class="coupon4u-view">
	<div class="coupon4u-couponid">
		<?php echo Mage::helper('coupons4u')->__('CouponID');?>:<?php echo $_coupon4u->getCouponid();?>
	</div>

</div>